Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.box_check_update = false

  config.vm.network "private_network", ip: "192.168.10.10"

  config.vm.synced_folder "../..", "/CodePier"

  config.vm.provision "file", source: "./id_rsa.pub", destination: "~/codepier.pub"

  config.vm.provision "shell", inline: "mv /home/ubuntu/codepier.pub /root/.ssh/authorized_keys && chown root:root /root/.ssh/authorized_keys"
end
