# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.box_check_update = false

  config.vm.network "private_network", ip: "192.168.10.10"

  config.vm.synced_folder "../..", "/CodePier"

  config.vm.provision "file", source: "./id_rsa.pub", destination: "~/.ssh/me.pub"
  config.vm.provision "shell", inline: "rm /root/.ssh/authorized_keys"
  config.vm.provision "shell", inline: "cat /home/ubuntu/.ssh/me.pub >> /root/.ssh/authorized_keys"
end
